### ISSUE TITLE
Version without 3D models

### ISSUE THREAD

**Issue by snigelpasta** [pokeheadroom/RENDER96-HD-TEXTURE-PACK#5]
Hello.
I am only interested in using the new textures but not the hi-poly 3D models.

Would that be possible using this pack?

**Comment by pokeheadroom** [comment]
the files are all there but as of right now theres no way to switch between the models and the textures, maybe something to keep in mind for the next update or the one after that

**Comment by pokeheadroom** [comment]
if you want to use only the textures witout any of the models then try only installing the texture pack in your sm64pcbuilder settings and ignore the conversion tab or the modelpacks tab
